### ISSUE TITLE
Error when using MinkowskiEngine v0.5.0

### ISSUE THREAD

**Issue by robertsenputras** [aniqueakhtar/PointCloudUpsampling#2]
Hi.

Could you mention what kind of modification that I need to do in the model to run the algorithm with MinkowskiEngine v0.5.0 ? I got errors if I just using vanilla code.

Thank you

**Comment by mdane-x** [comment]
Hi,

You have a change log here:
https://github-wiki-see.page/m/NVIDIA/MinkowskiEngine/wiki/Migration-Guide-from-v0.4.x-to-0.5.x

**Comment by aniqueakhtar** [comment]
> 
> Could you mention what kind of modification that I need to do in the model to run the algorithm with MinkowskiEngine v0.5.0 ? I got errors if I just using vanilla code.
> 

I believe @mdane-x already answered this question above.
However, I can upload an updated version of the code over the summer after migrating it to v0.5 of Minkowski.
