### ISSUE TITLE
How to convert .ply files to .bin format

### ISSUE THREAD

**Issue by MURALI14** [aniqueakhtar/PointCloudUpsampling#3]
By using convert_kitti.py converted the kitti point cloud to .ply format 
 
and up sampled it using eval_kitti.py, where the up sampled pcd is also in .ply format but i need it to be in bin format 

how can we convert .ply file to .bin

**Comment by aniqueakhtar** [comment]
I am not sure how to do that. Depending on what final format you want it, you can probably use an appropriate library to achieve the task.
