### ISSUE TITLE
what is the use of dataset_8i?

### ISSUE THREAD

**Issue by pandaypr** [aniqueakhtar/PointCloudUpsampling#6]
Hello, 
Greetings!

I'm trying to train the model from scratch on a custom Kitti dataset, while studying the code, I see 'dataset_8i' and 'dataset_8i_GT' used by default. What is its significance and Can I skip that part and run it only with Kitti dataset.?

Best Regards,
Panday

**Comment by aniqueakhtar** [comment]
Hello,
Just to quickly answer this question. dataset_8i_GT is the original 8i dataset which is high resolution. dataset_8i is the downsampled training dataset I generated using a file that should be uploaded in this repository. 

I also updated this code for Minkowski 0.5. I think I'll try to upload the newer code in a week or so to make it easier to replicate this work.

**Comment by pandaypr** [comment]
Thank you so much, for the information.
